name: Selenium Test Suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # This gives write permission to the repository
      pages: write     # This gives permission to deploy to GitHub Pages
      id-token: write  # This is required for GitHub Pages deployment
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install Chrome and Chromedriver
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d '.' -f1)
          DRIVER_VERSION=$(curl -s "https://googlechromelabs.github.io/chrome-for-testing/LATEST_RELEASE_${CHROME_VERSION}")
          echo "Chrome version: $(google-chrome --version)"
          echo "Chromedriver version: $DRIVER_VERSION"
          wget -O chromedriver.zip "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/${DRIVER_VERSION}/linux64/chromedriver-linux64.zip"
          unzip chromedriver.zip
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
          chmod +x /usr/local/bin/chromedriver

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create Keyword-Driven Test Data
        run: python create_fresh_test_data.py

      - name: Enforce Headless Mode for Tests
        run: |
          sed -i 's/^headless_mode = False/headless_mode = True/' selenium_demoblaze_framework/config/config.ini

      - name: Run Pytest and Generate Reports
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          pytest selenium_demoblaze_framework/tests/ \
            --html=reports/test-report.html \
            --self-contained-html \
            --alluredir=reports/allure-results

      - name: Upload HTML Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: html-test-report
          path: reports/test-report.html

      - name: Get Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate Allure Report
        if: always()
        uses: simple-elf/allure-report-action@v1.7
        with:
          allure_results: reports/allure-results
          allure_history: allure-history
          keep_reports: 20
          gh_pages: gh-pages

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Prepare Reports for GitHub Pages
        if: always()
        run: |
          mkdir -p deploy
          
          # Copy allure history
          if [ -d "allure-history" ]; then
            cp -r allure-history/* deploy/ 2>/dev/null || true
          fi
          
          # Create HTML reports directory
          mkdir -p deploy/html-reports
          cp reports/test-report.html deploy/html-reports/report-${{ github.run_number }}.html
          
          # Create an index page WITHOUT auto-redirect
          cat > deploy/index.html <<EOF
          <!DOCTYPE html>
          <html>
          <head>
              <title>Test Reports Dashboard - Selenium DemoBlaze</title>
              <meta charset="utf-8">
              <meta name="viewport" content="width=device-width, initial-scale=1">
              <style>
                  * {
                      margin: 0;
                      padding: 0;
                      box-sizing: border-box;
                  }
                  body {
                      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;
                      line-height: 1.6;
                      color: #333;
                      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                      min-height: 100vh;
                      display: flex;
                      align-items: center;
                      justify-content: center;
                      padding: 20px;
                  }
                  .container {
                      background: white;
                      border-radius: 12px;
                      padding: 40px;
                      box-shadow: 0 20px 60px rgba(0,0,0,0.3);
                      max-width: 800px;
                      width: 100%;
                      animation: fadeIn 0.5s ease-in;
                  }
                  @keyframes fadeIn {
                      from { opacity: 0; transform: translateY(20px); }
                      to { opacity: 1; transform: translateY(0); }
                  }
                  h1 {
                      color: #2c3e50;
                      text-align: center;
                      margin-bottom: 10px;
                      font-size: 2.5em;
                  }
                  .subtitle {
                      text-align: center;
                      color: #7f8c8d;
                      margin-bottom: 30px;
                      font-size: 1.1em;
                  }
                  .info-box {
                      background: #f8f9fa;
                      border-left: 4px solid #667eea;
                      padding: 20px;
                      border-radius: 8px;
                      margin-bottom: 30px;
                  }
                  .info-box p {
                      margin: 5px 0;
                      color: #555;
                  }
                  .info-box strong {
                      color: #333;
                      font-weight: 600;
                  }
                  .reports-section {
                      display: grid;
                      grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
                      gap: 20px;
                      margin-bottom: 30px;
                  }
                  .report-card {
                      background: white;
                      border: 2px solid #e0e0e0;
                      border-radius: 10px;
                      padding: 25px;
                      text-align: center;
                      transition: all 0.3s ease;
                      cursor: pointer;
                  }
                  .report-card:hover {
                      transform: translateY(-5px);
                      box-shadow: 0 10px 30px rgba(0,0,0,0.15);
                      border-color: #667eea;
                  }
                  .report-card h3 {
                      color: #2c3e50;
                      margin-bottom: 10px;
                      font-size: 1.5em;
                  }
                  .report-card p {
                      color: #7f8c8d;
                      margin-bottom: 20px;
                      font-size: 0.95em;
                  }
                  .btn {
                      display: inline-block;
                      padding: 12px 30px;
                      color: white;
                      text-decoration: none;
                      border-radius: 6px;
                      font-weight: 500;
                      transition: all 0.3s ease;
                      font-size: 1em;
                  }
                  .btn-allure {
                      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                  }
                  .btn-allure:hover {
                      transform: scale(1.05);
                      box-shadow: 0 5px 15px rgba(102, 126, 234, 0.4);
                  }
                  .btn-html {
                      background: linear-gradient(135deg, #27ae60 0%, #2ecc71 100%);
                  }
                  .btn-html:hover {
                      transform: scale(1.05);
                      box-shadow: 0 5px 15px rgba(46, 204, 113, 0.4);
                  }
                  .history-section {
                      margin-top: 30px;
                      padding-top: 30px;
                      border-top: 2px solid #e0e0e0;
                  }
                  .history-section h3 {
                      color: #2c3e50;
                      margin-bottom: 15px;
                      text-align: center;
                  }
                  .history-links {
                      display: flex;
                      flex-wrap: wrap;
                      gap: 10px;
                      justify-content: center;
                  }
                  .history-link {
                      padding: 8px 16px;
                      background: #f8f9fa;
                      border: 1px solid #ddd;
                      border-radius: 5px;
                      text-decoration: none;
                      color: #555;
                      transition: all 0.3s ease;
                      font-size: 0.9em;
                  }
                  .history-link:hover {
                      background: #667eea;
                      color: white;
                      border-color: #667eea;
                  }
                  .timestamp {
                      text-align: center;
                      color: #95a5a6;
                      font-size: 0.85em;
                      margin-top: 20px;
                  }
                  .emoji {
                      font-size: 1.5em;
                      margin-bottom: 10px;
                  }
              </style>
          </head>
          <body>
              <div class="container">
                  <h1>🧪 Test Reports Dashboard</h1>
                  <p class="subtitle">Selenium DemoBlaze Automation</p>
                  
                  <div class="info-box">
                      <p><strong>📦 Repository:</strong> ${{ github.repository }}</p>
                      <p><strong>🏃 Run Number:</strong> #${{ github.run_number }}</p>
                      <p><strong>🌿 Branch:</strong> ${{ github.ref_name }}</p>
                      <p><strong>🔨 Commit:</strong> <code>${{ github.sha }}</code></p>
                      <p><strong>👤 Actor:</strong> ${{ github.actor }}</p>
                  </div>

                  <div class="reports-section">
                      <div class="report-card">
                          <div class="emoji">📊</div>
                          <h3>Allure Report</h3>
                          <p>Interactive test report with detailed execution info, trends, and history</p>
                          <a href="${{ github.run_number }}/" class="btn btn-allure">Open Allure Report</a>
                      </div>
                      
                      <div class="report-card">
                          <div class="emoji">📄</div>
                          <h3>HTML Report</h3>
                          <p>Simple, self-contained HTML test report generated by pytest-html</p>
                          <a href="html-reports/report-${{ github.run_number }}.html" class="btn btn-html">Open HTML Report</a>
                      </div>
                  </div>

                  <div class="history-section">
                      <h3>📚 Previous Reports</h3>
                      <div class="history-links" id="history-links">
                          <!-- Will be populated by JavaScript -->
                      </div>
                  </div>

                  <div class="timestamp">
                      Generated on: <span id="timestamp"></span>
                  </div>
              </div>

              <script>
                  // Set timestamp
                  document.getElementById('timestamp').textContent = new Date().toLocaleString();
                  
                  // Generate history links
                  const currentRun = ${{ github.run_number }};
                  const historyContainer = document.getElementById('history-links');
                  
                  // Show last 10 runs
                  for(let i = currentRun - 1; i > Math.max(0, currentRun - 10); i--) {
                      const linkDiv = document.createElement('div');
                      linkDiv.style.display = 'inline-block';
                      linkDiv.innerHTML = \`
                          <a href="\${i}/" class="history-link" title="View Run #\${i}">
                              Run #\${i}
                          </a>
                      \`;
                      historyContainer.appendChild(linkDiv);
                  }
                  
                  if (currentRun <= 1) {
                      historyContainer.innerHTML = '<p style="color: #95a5a6;">No previous reports available</p>';
                  }
              </script>
          </body>
          </html>
          EOF

      - name: Deploy to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: deploy
          force_orphan: true  # Always use force_orphan for first deployment

      - name: Post Report URLs
        if: always()
        run: |
          echo "### 📊 Test Reports Published! 🎉" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**🌐 Main Dashboard:** https://roykunaljit.github.io/selenium-demoblaze-automation/" >> $GITHUB_STEP_SUMMARY
          echo "**📈 Allure Report:** https://roykunaljit.github.io/selenium-demoblaze-automation/${{ github.run_number }}/" >> $GITHUB_STEP_SUMMARY
          echo "**📄 HTML Report:** https://roykunaljit.github.io/selenium-demoblaze-automation/html-reports/report-${{ github.run_number }}.html" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "---" >> $GITHUB_STEP_SUMMARY
          echo "Run Number: #${{ github.run_number }}" >> $GITHUB_STEP_SUMMARY
          echo "Commit: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY